config/routes.rb
Rails.application.routes.draw do
  namespace :sayonghelloworld do
    get 'hello/scratch' => 'hello#scratch', as: :return
    post 'hello/scratch' => 'hello#scratch', as: :return_post
  end
  namespace :sayonghelloworld do
    get 'hello/rub/:id' => 'hello#rub', as: :path_view_record
    post 'hello/rub/:id' => 'hello#rub', as: :path_post_view_record
    patch 'hello/rub/:id' => 'hello#rub', as: :return_view
  end
  namespace :sayonghelloworld do
    post 'hello/edit/:id' => 'hello#edit', as: :path_edit_record
  end

  namespace :sayonghelloworld do
    post 'hello/create' => 'hello#create', as: :create_record
  end

  namespace :sayonghelloworld do
    get 'hello/created' => 'hello#created', as: :created
    post 'hello/created' => 'hello#created', as: :created_post
  end

  root 'sayonghelloworld/hello#scratch'

end

app/models/hello.rb
class Hello < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sayonghelloworld/hello_controller.rb
class Sayonghelloworld::HelloController < ApplicationController

  def scratch

    if params.has_key?(:deleteAll)
      Hello.delete_all
    end

    if params.has_key?(:id)
      Hello.delete(params[:id].to_i)
    end

    @all_hello_items = Hello.all
  end

  def rub

    if params.has_key?(:description)
      description = params[:description]
    end
    if params.has_key?(:name)
      name = params[:name]
      name = name.to_s.capitalize
    end

    if params.has_key?(:hello)
      hello = params[:hello]
      description = hello[:description]
      name = hello[:name]
    end


    if params.has_key?(:id)
      id = params[:id].to_i
      if Hello.all.empty?
        Hello.create(name: name, description: description)
      else
        if id>= Hello.first.id.to_i && id <= Hello.last.id.to_i
          Hello.find(id).update(name: name, description: description)
        else
          Hello.create(name: name, description: description)
        end
      end
    end

    @record = Hello.last
    if params.has_key?(:id)
      @record = Hello.find(params[:id].to_i)
    end
  end

  def edit
    @record = Hello.last
    if params.has_key?(:id)
      @record = Hello.find(params[:id].to_i)
    end
  end

  def create
    @record = Hello.new
  end

  def created
    if params.has_key?(:hello)
      hello = params[:hello]
      description = hello[:description]
      name = hello[:name]
      created = Hello.create(description: description, name: name)
      @message = created.errors.messages
      if @message.empty?
        @message = 'Welcome in my Twitter :D!'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sayonghelloworld/hello_helper.rb
module Sayonghelloworld::HelloHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombieTwitter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sayonghelloworld/hello/create.html.erb
<div align="center">
  <img src="http://s24.postimg.org/yl99int9w/zombie_header.jpg" width="640">

  <h1>Create record </h1>

  <%= form_for @record, url: {action: :created} do |f| %>
      Name:<br>
      <%= f.text_field :name %><br>
      Description:<br>
      <%= f.text_field :description %><br><br><br>
      <table>
        <%= f.submit 'Save' %>
  <% end %>
  <%= button_to 'Cancel', sayonghelloworld_return_path %>
  </table><br>
</div>

app/views/sayonghelloworld/hello/created.html.erb
<div align="center">
  <img src="http://s24.postimg.org/yl99int9w/zombie_header.jpg" width="640"><br><br>
  <font size="15" color="red"><%= @message %></font>

  <%= button_to 'Done', sayonghelloworld_return_path %>
</div>

app/views/sayonghelloworld/hello/edit.html.erb
<div align="center">
  <img src="http://s24.postimg.org/yl99int9w/zombie_header.jpg" width="640">

  <h1>Edit <%= @record.name %> </h1>

  <%= form_for @record, url: {action: :rub, id: @record.id} do |f| %>
      Name:<br>
      <%= f.text_field :name %><br>
      Description:<br>
      <%= f.text_field :description %><br><br><br>
      <table>
        <%= f.submit 'Save' %>
  <% end %>
  <%= button_to 'Cancel', sayonghelloworld_path_post_view_record_path(id: @record.id) %>
  </table><br>
</div>

app/views/sayonghelloworld/hello/rub.html.erb
<div align="center">
  <img src="http://s24.postimg.org/yl99int9w/zombie_header.jpg" width="640">

  <h1><%= @record.name %></h1>

  <p><%= @record.description %></p>
</div><br><br>

<div align="center">
  <table>
    <%= button_to 'Edit', sayonghelloworld_path_edit_record_path(id: @record.id) %>
    <%= button_to 'Back', sayonghelloworld_return_path %>
  </table>
  <br>
  <%= button_to 'Delete', sayonghelloworld_return_path(id: @record.id), :confirm => 'Are you sure, you want to dlete ' %>
</div>

app/views/sayonghelloworld/hello/scratch.html.erb
<div align="center">
  <img src="http://s24.postimg.org/yl99int9w/zombie_header.jpg" width="640">
  <table>
    <tr>
      <td>Name</td>
      <td>
        <small>click to view</small>
      </td>
    </tr>
    <% @all_hello_items.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td>
            <small><%= link_to 'View', sayonghelloworld_path_view_record_path(id: f.id) %></small>
          </td>
        </tr>
    <% end %>
  </table>
</div><br>
<div align="center">
  <%= button_to 'New ', sayonghelloworld_create_record_path %>
</div>